### ISSUE TITLE
packet size 255, test case 10 of COBS wikipedia

### ISSUE THREAD

**Issue by circuit4u-medium** [cbiffle/corncobs#1]
```
let mut input = [5; 255];
    input[253] = 0;
    input[254] = 100;
    let mut actual = vec![0; max_encoded_len(input.len())];
    let n = encode_buf(&input, &mut actual[..]);
```

results: **254, 5,...., 5, 2, 100, 0, 0**

If this stream of bytes are transmitted in packets of max. 255 bytes. 254, 5, ...., 5 (253 counts of "5"), 2   will be in one packet. 

As you can see the "2" is shifted up to fill the first packet. 

So the correct encoding should be **254, 5, ...., 5, 1, 2, 100, 0**

In other words, to encode, split the bytes into 254-byte first, then split by ZERO. 

Here is a detailed explanation link: https://circuit4us.medium.com/coding-consistent-overhead-byte-stuffing-cobs-for-packet-data-e60d7a361cf

**Comment by cbiffle** [comment]
Hi! Thanks for the report. I've read your post before, actually, and revisited it when preparing to publish this code. I think we disagree on some things. Let me try and explain.

For my purposes, a higher-level protocol generates variable-length packets, and then uses COBS to make their ends distinct on a data stream such as a serial port. This is what makes COBS attractive in embedded contexts without infinite memory: we can take the known maximum length of the higher level protocol, then feed it to `max_encoded_len`, and predict the maximum buffer we need to allocate for serial data reception. I also believe this is the use case described in the original paper, something I'll expand upon below.

You are applying COBS differently: higher-level protocol generates variable-length packets; COBS is applied; then they are separately packetized/framed _again_ into chunks of ~255 wire bytes, and so COBS needs to be aware of this. I believe this wrapper for `corncobs` implements what you're describing -- it reproduces the test vector you posted:

```rust
    let mut pos = 0;
    for chunk in input.chunks(254) {
        pos += encode_buf(&chunk, &mut output[pos..]);
        assert_eq!(output[pos - 1], 0); // just FYI
        pos -= 1; // remove literal zero from the output
    }
    // reinclude final zero
    pos += 1;
    let output = &output[..pos];
```

I have two concerns with this.

First, the encoded data you posted, `[254, 5, ...., 5, 1, 2, 100, 0]`, does not decode correctly when fed to the C function from the paper -- it inserts an extra zero before the final 100. This is without the additional framing logic you're suggesting, and which I've attempted to implement in the code snippet above, because it doesn't appear in the paper; I feel like it would have been included if it were part of the original method.

Second, given that 0 is no longer useful for frame boundary detection (your example ends in 2), it's not clear to me how you detect the 255-byte frame boundaries after desynchronization (e.g. UART framing error, receiver or transmitter reboot). The reason I'm using COBS (or SLIP framing, back before I knew about COBS) is to get reliable detection of frame boundaries from an arbitrary starting state.

I have re-read the paper and I believe I see the parts that you're interpreting as requiring decodes to only move in units of 254 bytes, but I think you've misinterpreted the terms "packet" vs "code block" they're using. The paper talks about

> logically appending a zero to every _packet_

(emphasis mine)

and also says

> The encoding routine searches through the first 254 bytes of the packet looking for the first occurrence of a zero byte. If no
zero is found, then a code of 0xFF is output, followed by the 254 non-zero bytes. If a zero is found, then the number of
bytes examined, n, is output as the code byte, followed by the actual values of the ( n–1) non-zero bytes up to, but not including, the zero byte. _The zero is then skipped and this process is repeated until all the bytes of the packet_ (including the final zero which is logically appended to every packet) have been encoded.

(emphasis added again)

This suggests that the packet is of arbitrary length (potentially greater than 254 bytes) or there'd be no need to process after the first 254. Units of 254 bytes are referred to as "code blocks" in the paper and don't get a logical zero. By encoding each section of 254 separately, you're applying the "logical zero" they're discussing to each 254-byte code block, while they're applying it to each packet. `corncobs` is doing the latter.

The `StuffData` C function in the paper is also clearly designed to handle packets of > 255 bytes -- note that when it advances `code` to `0xFF` it continues, rather than breaking the loop or aborting.

Please let me know if I've misunderstood what you're suggesting.

**Comment by circuit4u-medium** [comment]
Thanks for the detailed explanation. I agree 100% with what you've described. 

When I used COBS in my protocol, I construed a frame structure where the **first byte** is always the running count of ZEROs. 

So I choose to chunk data first, then run COBS. 

But COBS as described in the original paper, is implemented correctly here. And it has a broader use case, where streaming data itself doesn't have a TAG/HEADER byte in the front.
